use_frameworks!

target 'PickerViewKit_Example' do
  pod 'PickerViewKit', :path => '../'

  target 'PickerViewKit_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
  end
end
