use_frameworks!

target 'PickerViewKit_Example' do
  pod 'PickerViewKit', :path => '../'

  target 'UnitTests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.3'
    pod 'Nimble', '~> 7.3'
  end
end
